export const USER_INVOICE_REQUEST = 'USER_INVOICE_REQUEST'
export const USER_INVOICE_SUCCESS = 'USER_INVOICE_SUCCESS'
export const USER_INVOICE_FAIL = 'USER_INVOICE_FAIL'

export const USER_INVOICE_DETAILS_REQUEST = 'USER_INVOICE_DETAILS_REQUEST'
export const USER_INVOICE_DETAILS_SUCCESS = 'USER_INVOICE_DETAILS_SUCCESS'
export const USER_INVOICE_DETAILS_FAIL = 'USER_INVOICE_DETAILS_FAIL'

export const ADD_USER_INVOICE_REQUEST = 'ADD_USER_INVOICE_REQUEST'
export const ADD_USER_INVOICE_SUCCESS = 'ADD_USER_INVOICE_SUCCESS'
export const ADD_USER_INVOICE_FAIL = 'ADD_USER_INVOICE_FAIL'

export const ALL_INVOICE_REQUEST = 'ALL_INVOICE_REQUEST'
export const ALL_INVOICE_SUCCESS = 'ALL_INVOICE_SUCCESS'
export const ALL_INVOICE_FAIL = 'ALL_INVOICE_FAIL'

export const INVOICE_DETAILS_REQUEST = 'INVOICE_DETAILS_REQUEST'
export const INVOICE_DETAILS_SUCCESS = 'INVOICE_DETAILS_SUCCESS'
export const INVOICE_DETAILS_FAIL = 'INVOICE_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
