export const USER_INVOICE_REQUEST = 'USER_INVOICE_REQUEST'
export const USER_INVOICE_SUCCESS = 'USER_INVOICE_SUCCESS'
export const USER_INVOICE_FAIL = 'USER_INVOICE_FAIL'

export const ALL_INVOICE_REQUEST = 'ALL_INVOICE_REQUEST'
export const ALL_INVOICE_SUCCESS = 'ALL_INVOICE_SUCCESS'
export const ALL_INVOICE_FAIL = 'ALL_INVOICE_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
