export const ALL_USER_INVOICES_REQUEST = 'ALL_USER_INVOICES_REQUEST'
export const ALL_USER_INVOICES_SUCCESS = 'ALL_USER_INVOICES_SUCCESS'
export const ALL_USER_INVOICES_FAIL = 'ALL_USER_INVOICES_FAIL'

export const USER_INVOICE_DETAILS_REQUEST = 'USER_INVOICE_DETAILS_REQUEST'
export const USER_INVOICE_DETAILS_SUCCESS = 'USER_INVOICE_DETAILS_SUCCESS'
export const USER_INVOICE_DETAILS_FAIL = 'USER_INVOICE_DETAILS_FAIL'

export const USER_ADD_INVOICE_REQUEST = 'USER_ADD_INVOICE_REQUEST'
export const USER_ADD_INVOICE_SUCCESS = 'USER_ADD_INVOICE_SUCCESS'
export const USER_ADD_INVOICE_FAIL = 'USER_ADD_INVOICE_FAIL'
export const USER_ADD_INVOICE_RESET = 'USER_ADD_INVOICE_RESET'

export const ALL_ADMIN_INVOICES_REQUEST = 'ALL_ADMIN_INVOICES_REQUEST'
export const ALL_ADMIN_INVOICES_SUCCESS = 'ALL_ADMIN_INVOICES_SUCCESS'
export const ALL_ADMIN_INVOICES_FAIL = 'ALL_ADMIN_INVOICES_FAIL'

export const ADMIN_INVOICE_DETAILS_REQUEST = 'ADMIN_INVOICE_DETAILS_REQUEST'
export const ADMIN_INVOICE_DETAILS_SUCCESS = 'ADMIN_INVOICE_DETAILS_SUCCESS'
export const ADMIN_INVOICE_DETAILS_FAIL = 'ADMIN_INVOICE_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
