export const ALL_PACKS_REQUEST = 'ALL_PACKS_REQUEST'
export const ALL_PACKS_SUCCESS = 'ALL_PACKS_SUCCESS'
export const ALL_PACKS_FAIL = 'ALL_PACK_FAIL'

export const ADMIN_ADD_PACK_REQUEST = 'ADMIN_ADD_PACK_REQUEST'
export const ADMIN_ADD_PACK_SUCCESS = 'ADMIN_ADD_PACK_SUCCESS'
export const ADMIN_ADD_PACK_FAIL = 'ADMIN_ADD_PACK_FAIL'
export const ADMIN_ADD_PACK_RESET = 'ADMIN_ADD_PACK_RESET'

export const ADMIN_UPDATE_PACK_REQUEST = 'ADMIN_UPDATE_PACK_REQUEST'
export const ADMIN_UPDATE_PACK_SUCCESS = 'ADMIN_UPDATE_PACK_SUCCESS'
export const ADMIN_UPDATE_PACK_FAIL = 'ADMIN_UPDATE_PACK_FAIL'
export const ADMIN_UPDATE_PACK_RESET = 'ADMIN_UPDATE_PACK_RESET'

export const ADMIN_DELETE_PACK_REQUEST = 'ADMIN_DELETE_PACK_REQUEST'
export const ADMIN_DELETE_PACK_SUCCESS = 'ADMIN_DELETE_PACK_SUCCESS'
export const ADMIN_DELETE_PACK_FAIL = 'ADMIN_DELETE_PACK_FAIL'
export const ADMIN_DELETE_PACK_RESET = 'ADMIN_DELETE_PACK_RESET'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
