export const ALL_POSTS_REQUEST = 'ALL_POSTS_REQUEST'
export const ALL_POSTS_SUCCESS = 'ALL_POSTS_SUCCESS'
export const ALL_POSTS_FAIL = 'ALL_POSTS_FAIL'

export const POST_DETAILS_REQUEST = 'POST_DETAILS_REQUEST'
export const POST_DETAILS_SUCCESS = 'POST_DETAILS_SUCCESS'
export const POST_DETAILS_FAIL = 'POST_DETAILS_FAIL'

export const ALL_USER_POSTS_REQUEST = 'ALL_USER_POSTS_REQUEST'
export const ALL_USER_POSTS_SUCCESS = 'ALL_USER_POSTS_SUCCESS'
export const ALL_USER_POSTS_FAIL = 'ALL_USER_POSTS_FAIL'

export const DELETE_USER_POST_REQUEST = 'DELETE_USER_POST_REQUEST'
export const DELETE_USER_POST_SUCCESS = 'DELETE_USER_POST_SUCCESS'
export const DELETE_USER_POST_RESET = 'DELETE_USER_POST_RESET'
export const DELETE_USER_POST_FAIL = 'DELETE_USER_POST_FAIL'

export const RESET_USER_POST = 'RESET_USER_POST'

export const POST_EDIT_REQUEST = 'POST_EDIT_REQUEST'
export const POST_EDIT_SUCCESS = 'POST_EDIT_SUCCESS'
export const POST_EDIT_RESET = 'POST_EDIT_RESET'
export const POST_EDIT_FAIL = 'POST_EDIT_FAIL'

export const ADD_NEW_POST_REQUEST = 'ADD_NEW_POST_REQUEST'
export const ADD_NEW_POST_SUCCESS = 'ADD_NEW_POST_SUCCESS'
export const ADD_NEW_POST_RESET = 'ADD_NEW_POST_RESET'
export const ADD_NEW_POST_FAIL = 'ADD_NEW_POST_FAIL'

export const ALL_UNAPPROVED_POSTS_REQUEST = 'ALL_UNAPPROVED_POSTS_REQUEST'
export const ALL_UNAPPROVED_POSTS_SUCCESS = 'ALL_UNAPPROVED_POSTS_SUCCESS'
export const ALL_UNAPPROVED_POSTS_FAIL = 'ALL_UNAPPROVED_POSTS_FAIL'

export const MODERATOR_APPROVE_POST_REQUEST = 'MODERATOR_APPROVE_POST_REQUEST'
export const MODERATOR_APPROVE_POST_SUCCESS = 'MODERATOR_APPROVE_POST_SUCCESS'
export const MODERATOR_APPROVE_POST_FAIL = 'MODERATOR_APPROVE_POST_FAIL'
export const MODERATOR_APPROVE_POST_RESET = 'MODERATOR_APPROVE_POST_RESET'

export const MODERATOR_REPORT_POST_REQUEST = 'MODERATOR_REPORT_POST_REQUEST'
export const MODERATOR_REPORT_POST_SUCCESS = 'MODERATOR_REPORT_POST_SUCCESS'
export const MODERATOR_REPORT_POST_FAIL = 'MODERATOR_REPORT_POST_FAIL'
export const MODERATOR_REPORT_POST_RESET = 'MODERATOR_REPORT_POST_RESET'

export const DELETE_ADMIN_POST_REQUEST = 'DELETE_ADMIN_POST_REQUEST'
export const DELETE_ADMIN_POST_SUCCESS = 'DELETE_ADMIN_POST_SUCCESS'
export const DELETE_ADMIN_POST_RESET = 'DELETE_ADMIN_POST_RESET'
export const DELETE_ADMIN_POST_FAIL = 'DELETE_ADMIN_POST_FAIL'

export const UPDATE_ADMIN_POST_REQUEST = 'UPDATE_ADMIN_POST_REQUEST'
export const UPDATE_ADMIN_POST_SUCCESS = 'UPDATE_ADMIN_POST_SUCCESS'
export const UPDATE_ADMIN_POST_RESET = 'UPDATE_ADMIN_POST_RESET'
export const UPDATE_ADMIN_POST_FAIL = 'UPDATE_ADMIN_POST_FAIL'

export const ADD_NEW_POST_ADMIN_REQUEST = 'ADD_NEW_POST_ADMIN_REQUEST'
export const ADD_NEW_POST_ADMIN_SUCCESS = 'ADD_NEW_POST_ADMIN_SUCCESS'
export const ADD_NEW_POST_ADMIN_RESET = 'ADD_NEW_POST_ADMIN_RESET'
export const ADD_NEW_POST_ADMIN_FAIL = 'ADD_NEW_POST_ADMIN_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
