export const ALL_POSTS_REQUEST = 'ALL_POSTS_REQUEST'
export const ALL_POSTS_SUCCESS = 'ALL_POSTS_SUCCESS'
export const ALL_POSTS_FAIL = 'ALL_POSTS_FAIL'

export const POST_DETAILS_REQUEST = 'POST_DETAILS_REQUEST'
export const POST_DETAILS_SUCCESS = 'POST_DETAILS_SUCCESS'
export const POST_DETAILS_FAIL = 'POST_DETAILS_FAIL'

export const ALL_USER_POSTS_REQUEST = 'ALL_USER_POSTS_REQUEST'
export const ALL_USER_POSTS_SUCCESS = 'ALL_USER_POSTS_SUCCESS'
export const ALL_USER_POSTS_FAIL = 'ALL_USER_POSTS_FAIL'

export const DELETE_USER_POST_REQUEST = 'DELETE_USER_POST_REQUEST'
export const DELETE_USER_POST_SUCCESS = 'DELETE_USER_POST_SUCCESS'
export const DELETE_USER_POST_RESET = 'DELETE_USER_POST_RESET'
export const DELETE_USER_POST_FAIL = 'DELETE_USER_POST_FAIL'

export const RESET_USER_POST = 'RESET_USER_POST'

export const POST_EDIT_REQUEST = 'POST_EDIT_REQUEST'
export const POST_EDIT_SUCCESS = 'POST_EDIT_SUCCESS'
export const POST_EDIT_RESET = 'POST_EDIT_RESET'
export const POST_EDIT_FAIL = 'POST_EDIT_FAIL'

export const ADD_NEW_POST_REQUEST = 'ADD_NEW_POST_REQUEST'
export const ADD_NEW_POST_SUCCESS = 'ADD_NEW_POST_SUCCESS'
export const ADD_NEW_POST_RESET = 'ADD_NEW_POST_RESET'
export const ADD_NEW_POST_FAIL = 'ADD_NEW_POST_FAIL'

export const ALL_UNAPPROVED_POSTS_REQUEST = 'ALL_UNAPPROVED_POSTS_REQUEST'
export const ALL_UNAPPROVED_POSTS_SUCCESS = 'ALL_UNAPPROVED_POSTS_SUCCESS'
export const ALL_UNAPPROVED_POSTS_FAIL = 'ALL_UNAPPROVED_POSTS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
