export const PROVINCE_REQUEST = 'PROVINCE_REQUEST'
export const PROVINCE_SUCCESS = 'PROVINCE_SUCCESS'
export const PROVINCE_FAIL = 'PROVINCE_FAIL'

export const PROVINCE_DISTRICT_REQUEST = 'PROVINCE_DISTRICT_REQUEST'
export const PROVINCE_DISTRICT_SUCCESS = 'PROVINCE_DISTRICT_SUCCESS'
export const PROVINCE_DISTRICT_FAIL = 'PROVINCE_DISTRICT_FAIL'

export const PROVINCE_DISTRICT_WARD_REQUEST = 'PROVINCE_DISTRICT_WARD_REQUEST'
export const PROVINCE_DISTRICT_WARD_SUCCESS = 'PROVINCE_DISTRICT_WARD_SUCCESS'
export const PROVINCE_DISTRICT_WARD_FAIL = 'PROVINCE_DISTRICT_WARD_FAIL'
