export const REGISTER_USER_SAVE_TEMP_DATA = 'REGISTER_USER_SAVE_TEMP_DATA'
export const REGISTER_USER_SEND_OTP_REQUEST = 'REGISTER_USER_SEND_OTP_REQUEST'
export const REGISTER_USER_SEND_OTP_SUCCESS = 'REGISTER_USER_SEND_OTP_SUCCESS'
export const REGISTER_USER_SEND_OTP_FAIL = 'REGISTER_USER_SEND_OTP_FAIL'
export const REGISTER_USER_VERIFY_REQUEST = 'REGISTER_USER_VERIFY_REQUEST'
export const REGISTER_USER_VERIFY_SUCCESS = 'REGISTER_USER_VERIFY_SUCCESS'
export const REGISTER_USER_VERIFY_FAIL = 'REGISTER_USER_VERIFY_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
