export const REGISTER_USER_SEND_OTP_REQUEST = 'REGISTER_USER_SEND_OTP_REQUEST'
export const REGISTER_USER_SEND_OTP_SUCCESS = 'REGISTER_USER_SEND_OTP_SUCCESS'
export const REGISTER_USER_SEND_OTP_FAIL = 'REGISTER_USER_SEND_OTP_FAIL'
export const REGISTER_USER_VERIFY_REQUEST = 'REGISTER_USER_VERIFY_REQUEST'
export const REGISTER_USER_VERIFY_SUCCESS = 'REGISTER_USER_VERIFY_SUCCESS'
export const REGISTER_USER_VERIFY_FAIL = 'REGISTER_USER_VERIFY_FAIL'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

export const FORGOT_PASSWORD_SEND_OTP_REQUEST =
  'FORGOT_PASSWORD_SEND_OTP_REQUEST'
export const FORGOT_PASSWORD_SEND_OTP_SUCCESS =
  'FORGOT_PASSWORD_SEND_OTP_SUCCESS'
export const FORGOT_PASSWORD_SEND_OTP_FAIL = 'FORGOT_PASSWORD_SEND_OTP_FAIL'
export const FORGOT_PASSWORD_VERIFY_OTP_REQUEST =
  'FORGOT_PASSWORD_VERIFY_OTP_REQUEST'
export const FORGOT_PASSWORD_VERIFY_OTP_SUCCESS =
  'FORGOT_PASSWORD_VERIFY_OTP_SUCCESS'
export const FORGOT_PASSWORD_VERIFY_OTP_FAIL = 'FORGOT_PASSWORD_VERIFY_OTP_FAIL'
export const FORGOT_PASSWORD_RESET_REQUEST = 'FORGOT_PASSWORD_RESET_REQUEST'
export const FORGOT_PASSWORD_RESET_SUCCESS = 'FORGOT_PASSWORD_RESET_SUCCESS'
export const FORGOT_PASSWORD_RESET_FAIL = 'FORGOT_PASSWORD_RESET_FAIL'

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET'
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST'
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_RESET = 'UPDATE_PASSWORD_RESET'
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL'

export const GET_ALL_USER_REQUEST = 'GET_ALL_USER_REQUEST'
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS'
export const GET_ALL_USER_FAIL = 'GET_ALL_USER_FAIL'

export const UPDATE_PROFILE_USER_ADMIN_REQUEST =
  'UPDATE_PROFILE_USER_ADMIN_REQUEST'
export const UPDATE_PROFILE_USER_ADMIN_SUCCESS =
  'UPDATE_PROFILE_USER_ADMIN_SUCCESS'
export const UPDATE_PROFILE_USER_ADMIN_RESET = 'UPDATE_PROFILE_USER_ADMIN_RESET'
export const UPDATE_PROFILE_USER_ADMIN_FAIL = 'UPDATE_PROFILE_USER_ADMIN_FAIL'

export const BLOCK_USER_REQUEST = 'BLOCK_USER_REQUEST'
export const BLOCK_USER_SUCCESS = 'BLOCK_USER_SUCCESS'
export const BLOCK_USER_RESET = 'BLOCK_USER_RESET'
export const BLOCK_USER_FAIL = 'BLOCK_USER_FAIL'

export const UN_BLOCK_USER_REQUEST = 'UN_BLOCK_USER_REQUEST'
export const UN_BLOCK_USER_SUCCESS = 'UN_BLOCK_USER_SUCCESS'
export const UN_BLOCK_USER_RESET = 'UN_BLOCK_USER_RESET'
export const UN_BLOCK_USER_FAIL = 'UN_BLOCK_USER_FAIL'

export const GET_USER_ADMIN_REQUEST = 'GET_USER_ADMIN_REQUEST'
export const GET_USER_ADMIN_SUCCESS = 'GET_USER_ADMIN_SUCCESS'
export const GET_USER_ADMIN_FAIL = 'GET_USER_ADMIN_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
