export const REGISTER_USER_SAVE_TEMP_DATA = 'REGISTER_USER_SAVE_TEMP_DATA';
export const REGISTER_USER_SEND_OTP_REQUEST = 'REGISTER_USER_SEND_OTP_REQUEST';
export const REGISTER_USER_SEND_OTP_SUCCESS = 'REGISTER_USER_SEND_OTP_SUCCESS';
export const REGISTER_USER_SEND_OTP_FAIL = 'REGISTER_USER_SEND_OTP_FAIL';
export const REGISTER_USER_VERIFY_REQUEST = 'REGISTER_USER_VERIFY_REQUEST';
export const REGISTER_USER_VERIFY_SUCCESS = 'REGISTER_USER_VERIFY_SUCCESS';
export const REGISTER_USER_VERIFY_FAIL = 'REGISTER_USER_VERIFY_FAIL';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const FORGOT_PASSWORD_SEND_OTP_REQUEST =
  'FORGOT_PASSWORD_SEND_OTP_REQUEST';
export const FORGOT_PASSWORD_SEND_OTP_SUCCESS =
  'FORGOT_PASSWORD_SEND_OTP_SUCCESS';
export const FORGOT_PASSWORD_SEND_OTP_FAIL = 'FORGOT_PASSWORD_SEND_OTP_FAIL';
export const FORGOT_PASSWORD_VERIFY_OTP_REQUEST =
  'FORGOT_PASSWORD_VERIFY_OTP_REQUEST';
export const FORGOT_PASSWORD_VERIFY_OTP_SUCCESS =
  'FORGOT_PASSWORD_VERIFY_OTP_SUCCESS';
export const FORGOT_PASSWORD_VERIFY_OTP_FAIL =
  'FORGOT_PASSWORD_VERIFY_OTP_FAIL';
export const FORGOT_PASSWORD_RESET_REQUEST = 'FORGOT_PASSWORD_RESET_REQUEST';
export const FORGOT_PASSWORD_RESET_SUCCESS = 'FORGOT_PASSWORD_RESET_SUCCESS';
export const FORGOT_PASSWORD_RESET_FAIL = 'FORGOT_PASSWORD_RESET_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
